name: Build & Push API Image
on: [push]

env:
  REGISTRY: onlyusedtesla.azurecr.io
  IMAGE_NAME: out-api-v2
  TAG: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build
        run: |
          docker build \
            --build-arg BASE_REGISTRY=${{ env.REGISTRY }} \
            -t $REGISTRY/$IMAGE_NAME:$TAG .

      - name: Push
        run: docker push $REGISTRY/$IMAGE_NAME:$TAG
